# Build a service with environment variables
version: '1.0'

# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  init_variables:
    title: "Init variables"
    image: alpine
    commands:
      - cf_export BUILD_HARNESS_VERSION=0.5.5
      - cf_export GIT_BRANCH=${{CF_BRANCH}}

  clone:
      title: "Cloning repository"
      type: "git-clone"
      repo: "xaff/default-backend"
      # CF_BRANCH value is auto set when pipeline is triggered
      # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
      revision: "${{CF_BRANCH}}"
      git: "github"
      stage: "clone"

  print_pwd_files:
    title: 'Listing files'
    image: alpine:latest
    commands:
      - 'ls -l'

  build_image:
    title: Build image
    type: build
    description: Build image
    image_name: ${{CF_REPO_NAME}}
    dockerfile: Dockerfile
    working_directory: "./default-backend"

  semver:
    title: Export semantic version
    image: cloudposse/build-harness:${{BUILD_HARNESS_VERSION}}
    working_directory: ${{build_image}}
    commands:
      - make git/show
      - make semver/show
      - make semver/export >> ${{CF_VOLUME_PATH}}/env_vars_to_export

  push_image_commit:
    title: Push image with commit based semver tags
    type: push
    candidate: ${{build_image}}
    tags:
      - "${{SEMVERSION_COMMIT_SHORT}}"

  push_image_branch:
    title: Push image with branch based semver tags
    type: push
    candidate: ${{build_image}}
    tags:
      - "${{SEMVERSION_BRANCH_COMMIT_SHORT}}"
    when:
      condition:
        all:
          executeForBranch: "'${{SEMVERSION_BRANCH}}' != ''"

  push_image_tag_to_aws_test:
    title: Push image with tag based semver tags
    type: push
    registry: default-backend
    image_name: xaff/${{CF_REPO_NAME}}
    candidate: ${{build_image}}
    tag: "${{SEMVERSION_TAG}}"
    when:
      condition:
        all:
          executeForTag: "'${{SEMVERSION_TAG}}' != ''"

  push_image_latest_to_aws_test:
    title: Push image with latest tag
    type: push
    registry: default-backend
    image_name: xaff/${{CF_REPO_NAME}}
    candidate: ${{build_image}}
    tag: latest
    when:
      condition:
        all:
          executeForMasterBranch: "'${{CF_BRANCH}}' == 'master'"
